#!make

# This file is for inclusion from another makefile defining the environment and the COMPONENT, PROJECT_ROOT.
# See an example .env file in the gtrack project.
include ${PROJECT_ROOT}/dev-env/config/base/Makefile
