#!/usr/bin/env bash
set -e

export PROJECT_CONFIG=${TRAVIS_BRANCH}
# yarn run alltest
# yarn run cypress:run:ci

if [[ "$TRAVIS_EVENT_TYPE" == "pull_request" ]]; then
  yarn run lint
else
  # yarn build:container
  # yarn workspace app run build:android
  # npm run e2e:universal
  echo "Not a PR"
fi
