version: '3.1'

services:
  gtrack.website-prod:
    build:
      context: ..
      dockerfile: packages/website/Dockerfile.prod
    environment:
      - NODE_ENV
      - CI
    ports:
      - '9081:80'

  gtrack.admin-prod:
    build:
      context: ..
      dockerfile: packages/admin/Dockerfile.prod
    environment:
      - NODE_ENV
      - CI
    ports:
      - '9082:80'
