version: '3.1'

services:
  gtrack.universal-server:
    build:
      context: ..
      dockerfile: Dockerfile.universal
    environment:
      - NODE_ENV
      - CI
      - DEEPSTREAM_CONNECTION=ws://deepstream:6020/deepstream
    ports:
      - '4000:4000'
